apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka
data:
  kafka.json: |-
   {
      "bootstrap.servers": "seldon-kafka-plain-bootstrap.kafka:9092",
      "consumer":{
         "session.timeout.ms":6000,
         "auto.offset.reset":"earliest",
         "topic.metadata.refresh.interval.ms": 1000
      },
      "producer":{
        "linger.ms":0,
        "message.max.bytes":1000000000
      },
      "streams":{
      }
   }
