apiVersion: v1
items:
- apiVersion: v1
  kind: ReplicationController
  metadata:
    creationTimestamp: null
    labels:
      name: locust-master
      service: seldon
    name: locust-master
  spec:
    replicas: 1
    selector:
      name: locust-master
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: locust-master
          service: seldon
      spec:
        containers:
        - command:
          - locust
          - -f
          - /home/seldon/scripts/{{ .Values.locust.script }}
          - --hatch-rate
          - '{{ .Values.locust.hatchRate }}'
          - --clients
          - '{{ .Values.locust.clients }}'
          - --host
          - '{{ .Values.locust.host }}'
          - --master
          env:
          - name: OAUTH_KEY
            value: '{{ .Values.oauth.key }}'
          - name: OAUTH_SECRET
            value: '{{ .Values.oauth.secret }}'
          - name: DATA_SIZE
            value: '{{ .Values.data.size }}'
          image: seldonio/locust-core:{{ .Values.image.release }}
          imagePullPolicy: IfNotPresent
          name: locust-master
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /seldon-data
            name: storage
        dnsPolicy: ClusterFirst
        nodeSelector:
          role: locust
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - hostPath:
            path: /seldon-data
          name: storage
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      service: seldon
    name: locust-master
  spec:
    ports:
    - name: master-api1
      port: 5557
      protocol: TCP
      targetPort: 5557
    - name: master-api2
      port: 5558
      protocol: TCP
      targetPort: 5558
    - name: master-web
      nodePort: 30018
      port: 8089
      protocol: TCP
      targetPort: 8089
    selector:
      name: locust-master
    sessionAffinity: None
    type: NodePort
kind: List
metadata: {}
