apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    name: locust-slave
    service: seldon
  name: locust-slave
spec:
  replicas: 1
  selector:
    name: locust-slave
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: locust-slave
        service: seldon
    spec:
      containers:
      - command:
        - locust
        - -f
        - /home/seldon/scripts/{{ .Values.locust.script }}
        - --hatch-rate
        - '{{ .Values.locust.hatchRate }}'
        - --clients
        - '{{ .Values.locust.clients }}'
        - --host
        - '{{ .Values.locust.host }}'
        - --master-host
        - locust-master
        - --slave
        env:
        - name: OAUTH_KEY
          value: '{{ .Values.oauth.key }}'
        - name: OAUTH_SECRET
          value: '{{ .Values.oauth.secret }}'
        - name: DATA_SIZE
          value: '{{ .Values.data.size }}'
        image: seldonio/locust-core:{{ .Values.image.release }}
        imagePullPolicy: IfNotPresent
        name: locust-slave
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /seldon-data
          name: storage
      dnsPolicy: ClusterFirst
      nodeSelector:
        role: locust
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /seldon-data
        name: storage
