---
# Transformer and model

apiVersion: mlops.seldon.io/v1alpha1
kind: Pipeline
metadata:
  name: inferencegraph-sample
spec:
  steps:
    - name: start
      ref: transformer1
    - name: infer
      previous:
        - start
      ref: model1

---
# With drift detector async

apiVersion: mlops.seldon.io/v1alpha1
kind: Pipeline
metadata:
  name: transform-outlier-model-drift
spec:
  steps:
    - name: transform-input
      model: transformer
    - name: check-for-outlier
      inputs:
      - transform-input
      model: alibi-outlier-model
    - name: infer
      if: outlier.response.outlier == 0
      inputs:
      - transform-input
      model: my-model
    - name: drift
      inputs:
      - infer
      model: alibi-drift-model
      async: true

