scrape_configs:
  - job_name: 'agent'
    scrape_interval: 10s
    static_configs:
      - targets: ['agent-mlserver:9006']
      - targets: ['agent-triton:9007']
      - targets: ['pipelinegateway:9009']
