name: testconfig
spec:
  servers:
  - name: mlserver1
    replicas:
    - address: 0.0.0.0
      port: 9100
    - address: 0.0.0.0
      port: 9101
    - address: 0.0.0.0
      port: 9102
    - address: 0.0.0.0
      port: 9103      
  - name: triton
    replicas:
    - address: 0.0.0.0
      port: 9100
  models:
  - name: model1
    modelServer: mlserver1
    servers: [0]
  - name: model2
    modelServer: mlserver1
    servers: [0, 1, 3]
