opentelemetry:
  endpoint: seldon-collector:4317
  enable: true
  ratio: 1

hodometer:
  enabled: true
  image:
    pullPolicy: IfNotPresent
    registry: docker.io
    repository: seldonio/seldon-hodometer
    tag: latest
  logLevel: info
  metricsLevel: feature
  extraPublishUrls: ""

kafka:
  bootstrap: seldon-kafka-plain-bootstrap.kafka:9092
  consumer:
    sessionTimeoutMs: 6000
    autoOffsetReset: earliest
    topicMetadataRefreshIntervalMs: 1000
    topicMetadataPropagationMaxMs: 300000
  producer:
    lingerMs: 0
    messageMaxBytes: 1000000000

modelgateway:
  image:
    pullPolicy: IfNotPresent
    registry: docker.io
    repository: seldonio/seldon-modelgateway
    tag: latest
  workers: 8
  resources:
    requests:
      cpu: 100m
      memory: 1G

pipelinegateway:
  image:
    pullPolicy: IfNotPresent
    registry: docker.io
    repository: seldonio/seldon-pipelinegateway
    tag: latest
  resources:
    requests:
      cpu: 0.1
      memory: 1G

dataflow:
  image:
    pullPolicy: IfNotPresent
    registry: docker.io
    repository: seldonio/seldon-dataflow-engine
    tag: latest
  cores: 4
  resources:
    requests:
      cpu: 1
      memory: 1G

controller:
  image:
    pullPolicy: IfNotPresent
    registry: docker.io
    repository: seldonio/seldonv2-controller
    tag: latest
  resources:
    requests:
      cpu: 10m
      memory: 64Mi

envoy:
  image:
    pullPolicy: IfNotPresent
    registry: docker.io
    repository: seldonio/seldon-envoy
    tag: latest

scheduler:
  image:
    pullPolicy: IfNotPresent
    registry: docker.io
    repository: seldonio/seldon-scheduler
    tag: latest
  tls:
    scheduler:
      server:  
        secret:
        folder:
      client:
        secret:
        folder:
serverConfig:
  rclone:
    image:
      pullPolicy: IfNotPresent
      registry: docker.io
      repository: seldonio/seldon-rclone
      tag: latest

  agent:
    image:
      pullPolicy: IfNotPresent
      registry: docker.io
      repository: seldonio/seldon-agent
      tag: latest

  mlserver:
    image:
      pullPolicy: IfNotPresent
      registry: docker.io
      repository: cliveseldon/mlserver
      tag: 1.2.0.dev1
    serverCapabilities: "mlserver,alibi-detect,alibi-explain,lightgbm,mlflow,python,sklearn,spark-mlib,xgboost"
    overcommitPercentage: "10"
    modelVolumeStorage: 1Gi
    resources:
      memory: 1G

  triton:
    image:
      pullPolicy: IfNotPresent
      registry: nvcr.io
      repository: nvidia/tritonserver
      tag: 22.05-py3
    serverCapabilities: "triton,dali,fil,onnx,openvino,python,pytorch,tensorflow,tensorrt"
    overcommitPercentage: "10"
    modelVolumeStorage: 1Gi
    resources:
      memory: 1G
