---
- include_role:
    name: seldonio.k8s.strimzi_kafka
  when: install_kafka | bool

- name: Enable KRaft
  shell:
      " kubectl set env deployment/strimzi-cluster-operator STRIMZI_FEATURE_GATES=+UseStrimziPodSets,+UseKRaft -n {{ strimzi_kafka_namespace }} "
  tags: kraft
  when: ecosystem_enable_kraft | bool

- name: Create Kafka Cluster
  kubernetes.core.k8s:
    state: present
    namespace: "{{ kafka_namespace }}"
    template: "{{ repo_root_dir }}/{{ item }}"
  with_items:
    - kafka/strimzi/cluster.yaml
  when: ecosystem_configure_kafka | bool
