apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- pipelinegateway.yaml
- svc.yaml

images:
- name: pipelinegateway
  newName: seldonio/seldon-pipelinegateway
  newTag: latest
