apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipelinegateway
  namespace: system
  labels:
    app: pipelinegateway
spec:
  selector:
    matchLabels:
      app: pipelinegateway
  replicas: 1
  template:
    metadata:
      labels:
        app: pipelinegateway
    spec:
      securityContext:
        runAsUser: 8888
      containers:
      - command:
        - /bin/pipelinegateway
        args:
        - --http-port=9010
        - --grpc-port=9011
        - --metrics-port=9006
        - --config-path=/mnt/config/kafka.json
        image: pipelinegateway:latest
        imagePullPolicy: IfNotPresent
        name: pipelinegateway
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 9010
          name: http
          protocol: TCP
        - containerPort: 9011
          name: grpc
          protocol: TCP
        - containerPort: 9006
          name: metrics
          protocol: TCP
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "seldon-collector.seldon-mesh:4317"        
        volumeMounts:
        - name: config-volume
          mountPath: /mnt/config
      volumes:
      - name: config-volume
        configMap:
          name: seldon-kafka
      terminationGracePeriodSeconds: 5
      serviceAccountName: scheduler
