apiVersion: v1
kind: Secret
metadata:
  name: seldon-rclone-gs-public
  namespace: seldon-mesh
type: Opaque
stringData:
  gs: |
    type: "google cloud storage"
    name: gs
    parameters:
      anonymous: true
