apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: envoy
  namespace: seldon-mesh
spec:
  selector:
    matchLabels:
      app: seldon-mesh
  namespaceSelector:
    matchNames:
    - seldon-mesh
  endpoints:
  - port: admin
    interval: 15s
    path: /stats/prometheus
