apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: seldon-server
  namespaceSelector:
    matchNames: []
    any: false
  podMetricsEndpoints:    
  - port: server-metrics
    interval: 15s
    path: /metrics


