version: 2
jobs:
  build-api-frontend:
    docker:
      - image: seldonio/core-builder:0.1

    working_directory: /work

    environment:
      TESTVAR: OK

    steps:
      - checkout

      - run "cd api-frontend && make -f Makefile.ci build"

workflows:
  version: 2
  build:
    jobs:
      - build-api-frontend

