apiVersion: mlops.seldon.io/v1alpha1
kind: Model
metadata:
  name: income-preprocess
  namespace: seldon-mesh
spec:
  storageUri: "gs://seldon-models/scv2/examples/income/preprocessor"
  requirements:
  - sklearn
