version: "3.9"

services:

  agent:
    build:
      dockerfile: ./Dockerfile.agent
      context: .
    image: "${AGENT_IMAGE_AND_TAG}"
    command:
      - "/bin/agent"
      - "--log-level"
      - "debug"
      - "--config-path"
      - "/mnt/config"
      - "--rclone-host"
      - "rclone"
      - "--inference-host"
      - "server"
      - "--agent-host"
      - "agent"
    environment:
      - SELDON_OVERCOMMIT_PERCENTAGE=${AGENT_OVERCOMMIT_PERCENTAGE}
      - SELDON_REVERSE_PROXY_HTTP_PORT=${SELDON_REVERSE_PROXY_HTTP_PORT}
      - SELDON_REVERSE_PROXY_GRPC_PORT=${SELDON_REVERSE_PROXY_GRPC_PORT}
      - SELDON_SERVER_HTTP_PORT=${SERVER_HTTP_PORT}
      - SELDON_SERVER_GRPC_PORT=${SERVER_GRPC_PORT}
      - SELDON_DEBUG_GRPC_PORT=${AGENT_DEBUG_PORT}
      - SELDON_SCHEDULER_HOST=scheduler
      - SELDON_SCHEDULER_PORT=${SCHEDULER_AGENT_PORT}
      - MEMORY_REQUEST=${AGENT_MEMORY_REQUEST}

  envoy:
    build:
      dockerfile: ./Dockerfile.envoy-local
      context: .
    image: "${ENVOY_IMAGE_AND_TAG}"

  rclone:
    build:
      dockerfile: ./Dockerfile.rclone
      context: .
    image: "${RCLONE_IMAGE_AND_TAG}"

  scheduler:
    build:
      dockerfile: ./Dockerfile.scheduler
      context: .
    image: "${SCHEDULER_IMAGE_AND_TAG}"

  server:
    image: "${SERVER_IMAGE_AND_TAG}"

  modelgateway:
    build:
      dockerfile: ./Dockerfile.modelgateway
      context: .
    image: "${MODELGATEWAY_IMAGE_AND_TAG}"
    command:
      - "/bin/modelgateway"
      - "--log-level"
      - "debug"
      - "--config-path"
      - "/mnt/config"
      - "--scheduler-host"
      - "scheduler"
      - "--scheduler-port"
      - ${SCHEDULER_SERVER_PORT}
      - "--envoy-host"
      - "envoy"
      - "--envoy-port"
      - ${ENVOY_DATA_PORT}

  kafka:
    image: quay.io/strimzi/kafka:0.28.0-kafka-3.1.0
    command: [
      "sh", "-c",
      "./bin/kafka-storage.sh format -t $$(./bin/kafka-storage.sh random-uuid) -c ./config/kraft/server.properties && ./bin/kafka-server-start.sh ./config/kraft/server.properties"
    ]
    ports:
    - "9092:9092"    
    environment:
      LOG_DIR: "/tmp/logs"
            
