apiVersion: apps/v1
kind: Deployment
metadata:
  name: modelgateway
  namespace: system
  labels:
    control-plane: seldon-modelgateway
spec:
  selector:
    matchLabels:
      control-plane: seldon-modelgateway
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: seldon-modelgateway
    spec:
      securityContext:
        runAsUser: 8888
      containers:
      - command:
        - /bin/modelgateway
        args:
        - --scheduler-host=seldon-scheduler
        - --scheduler-port=9004
        - --envoy-host=seldon-mesh
        - --envoy-port=80
        - --config-path=/mnt/config/kafka.json
        image: modelgateway:latest
        imagePullPolicy: IfNotPresent
        name: modelgateway
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "seldon-collector.seldon-mesh:4317"        
        volumeMounts:
        - name: config-volume
          mountPath: /mnt/config
      volumes:
      - name: config-volume
        configMap:
          name: seldon-kafka
      terminationGracePeriodSeconds: 5
      serviceAccountName: scheduler
