apiVersion: apps/v1
kind: Deployment
metadata:
  name: modelgateway
  labels:
    control-plane: seldon-modelgateway
spec:
  selector:
    matchLabels:
      control-plane: seldon-modelgateway
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: seldon-modelgateway
    spec:
      securityContext:
        runAsUser: 8888
      containers:
      - command:
        - /bin/modelgateway
        args:
        - --scheduler-host=seldon-scheduler
        - --scheduler-port=9004
        - --envoy-host=seldon-mesh
        - --envoy-port=80
        - --kafka-config-path=/mnt/kafka/kafka.json
        - --tracing-config-path=/mnt/tracing/tracing.json
        image: modelgateway:latest
        imagePullPolicy: IfNotPresent
        name: modelgateway
        env:
          - name: MODELGATEWAY_NUM_WORKERS
            value: "8"
          - name: MODELGATEWAY_MAX_NUM_CONSUMERS
            value: "100"
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: kafka-config-volume
          mountPath: /mnt/kafka
        - name: tracing-config-volume
          mountPath: /mnt/tracing
      volumes:
      - name: kafka-config-volume
        configMap:
          name: seldon-kafka
      - name: tracing-config-volume
        configMap:
          name: seldon-tracing
      terminationGracePeriodSeconds: 5
      serviceAccountName: scheduler
