apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../componentsNoConfig

# May need to add x-kubernetes-patch values for new things you want to patch if missing
openapi:
  path: crd-schema.json

patchesStrategicMerge:
- patch_controller.yaml
- patch_dataflow.yaml
- patch_envoy.yaml
- patch_hodometer.yaml
- patch_modelgateway.yaml
- patch_mlserver.yaml
- patch_pipelinegateway.yaml
- patch_scheduler.yaml
- patch_triton.yaml

patches:
- path: patch_scheduler_service.yaml
  target:
    version: v1
    kind: Service
    name: scheduler
- path: patch_envoy_service.yaml
  target:
    version: v1
    kind: Service
    name: mesh
