apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../componentsNoConfig

openapi:
  path: crd-schema.json

patchesStrategicMerge:
- patch_dataflow.yaml
- patch_pipelinegateway.yaml
- patch_modelgateway.yaml
- patch_mlserver.yaml
- patch_triton.yaml
- patch_controller.yaml
- patch_envoy.yaml
- patch_scheduler.yaml
