apiVersion: apps/v1
kind: Deployment
metadata:
  name: seldon-hodometer
spec:
  template:
    spec:
      containers:
      - name: hodometer
        image: '{{ .Values.hodometer.image.registry }}/{{ .Values.hodometer.image.repository }}:{{.Values.hodometer.image.tag }}'
        imagePullPolicy: '{{ .Values.hodometer.image.pullPolicy }}'
        env:
          - name: METRICS_LEVEL
            value: '{{ .Values.hodometer.metricsLevel }}'
          - name: LOG_LEVEL
            value: '{{ .Values.hodometer.logLevel }}'
          - name: EXTRA_PUBLISH_URLS
            value: '{{ .Values.hodometer.extraPublishUrls }}'
          - name: CONTROL_PLANE_SECURITY_PROTOCOL
            value: '{{ .Values.security.controlplane.protocol }}'            
          - name: CONTROL_PLANE_TLS_SECRET_NAME
            value: '{{ .Values.security.controlplane.ssl.client.secret }}'
          - name: CONTROL_PLANE_TLS_KEY_LOCATION
            value: '{{ .Values.security.controlplane.ssl.key }}'
          - name: CONTROL_PLANE_TLS_CRT_LOCATION
            value: '{{ .Values.security.controlplane.ssl.crt }}'
          - name: CONTROL_PLANE_TLS_CA_LOCATION
            value: '{{ .Values.security.controlplane.ssl.ca }}'
