apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: seldon-scheduler
spec:
  template:
    spec:
      containers:
      - image: '{{ .Values.scheduler.image.registry }}/{{ .Values.scheduler.image.repository }}:{{ .Values.scheduler.image.tag }}'
        imagePullPolicy: '{{ .Values.scheduler.image.pullPolicy }}'
        name: scheduler
        env:
          - name: CONTROL_PLANE_SECURITY_PROTOCOL
            value: '{{ .Values.security.controlplane.protocol }}'            
          - name: CONTROL_PLANE_TLS_SECRET_NAME
            value: '{{ .Values.security.controlplane.ssl.server.secret }}'
          - name: CONTROL_PLANE_TLS_KEY_LOCATION
            value: '{{ .Values.security.controlplane.ssl.key }}'
          - name: CONTROL_PLANE_TLS_CRT_LOCATION
            value: '{{ .Values.security.controlplane.ssl.crt }}'
          - name: CONTROL_PLANE_TLS_CA_LOCATION
            value: '{{ .Values.security.controlplane.ssl.ca }}'
