apiVersion: apps/v1
kind: Deployment
metadata:
  name: seldon-pipelinegateway
spec:
  template:
    spec:
      containers:
      - image: '{{ .Values.pipelinegateway.image.registry }}/{{ .Values.pipelinegateway.image.repository }}:{{ .Values.pipelinegateway.image.tag }}'
        imagePullPolicy: '{{ .Values.pipelinegateway.image.pullPolicy }}'
        name: pipelinegateway
        resources:
          requests:
            cpu: '{{ .Values.pipelinegateway.resources.requests.cpu }}'
            memory: '{{ .Values.pipelinegateway.resources.requests.memory }}'
        env:
          - name: KAFKA_SECURITY_PROTOCOL
            value: '{{ .Values.security.kafka.protocol }}'            
          - name: KAFKA_CLIENT_TLS_SECRET_NAME
            value: '{{ .Values.security.kafka.ssl.client.secret }}'
          - name: KAFKA_CLIENT_TLS_KEY_LOCATION
            value: '{{ .Values.security.kafka.ssl.client.keyPath }}'
          - name: KAFKA_CLIENT_TLS_CRT_LOCATION
            value: '{{ .Values.security.kafka.ssl.client.crtPath }}'
          - name: KAFKA_CLIENT_TLS_CA_LOCATION
            value: '{{ .Values.security.kafka.ssl.client.caPath }}'
          - name: KAFKA_BROKER_TLS_SECRET_NAME
            value: '{{ .Values.security.kafka.ssl.client.brokerValidationSecret }}'
          - name: KAFKA_BROKER_TLS_CA_LOCATION
            value: '{{ .Values.security.kafka.ssl.client.brokerCaPath }}'
          - name: ENVOY_SECURITY_PROTOCOL
            value: '{{ .Values.security.envoy.protocol }}'            
          - name: ENVOY_UPSTREAM_SERVER_TLS_SECRET_NAME
            value: '{{ .Values.security.envoy.ssl.upstream.server.secret }}'
          - name: ENVOY_UPSTREAM_CLIENT_TLS_SECRET_NAME
            value: '{{ .Values.security.envoy.ssl.upstream.server.clientValidationSecret }}'
          - name: ENVOY_UPSTREAM_SERVER_TLS_KEY_LOCATION
            value: '{{ .Values.security.envoy.ssl.upstream.server.keyPath }}'
          - name: ENVOY_UPSTREAM_SERVER_TLS_CRT_LOCATION
            value: '{{ .Values.security.envoy.ssl.upstream.server.crtPath }}'
          - name: ENVOY_UPSTREAM_SERVER_TLS_CA_LOCATION
            value: '{{ .Values.security.envoy.ssl.upstream.server.caPath }}'
          - name: ENVOY_UPSTREAM_CLIENT_TLS_CA_LOCATION
            value: '{{ .Values.security.envoy.ssl.upstream.server.clientCaPath }}'
