apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: seldon-scheduler
spec:
  template:
    spec:
      containers:
      - image: '{{ .Values.scheduler.image.registry }}/{{ .Values.scheduler.image.repository }}:{{ .Values.scheduler.image.tag }}'
        imagePullPolicy: '{{ .Values.scheduler.image.pullPolicy }}'
        name: scheduler
