apiVersion: apps/v1
kind: Deployment
metadata:
  name: seldon-pipelinegateway
spec:
  template:
    spec:
      containers:
      - image: '{{ .Values.pipelinegateway.image.registry }}/{{ .Values.pipelinegateway.image.repository }}:{{ .Values.pipelinegateway.image.tag }}'
        imagePullPolicy: '{{ .Values.pipelinegateway.image.pullPolicy }}'
        name: pipelinegateway
        resources:
          requests:
            cpu: '{{ .Values.pipelinegateway.resources.requests.cpu }}'
            memory: '{{ .Values.pipelinegateway.resources.requests.memory }}'
        env:
          - name: KAFKA_SECURITY_PROTOCOL
            value: '{{ .Values.security.kafka.protocol }}'            
          - name: KAFKA_CLIENT_TLS_SECRET_NAME
            value: '{{ .Values.security.kafka.ssl.client.secret }}'
          - name: KAFKA_CLIENT_TLS_KEY_LOCATION
            value: '{{ .Values.security.kafka.ssl.client.key }}'
          - name: KAFKA_CLIENT_TLS_CRT_LOCATION
            value: '{{ .Values.security.kafka.ssl.client.crt }}'
          - name: KAFKA_CLIENT_TLS_CA_LOCATION
            value: '{{ .Values.security.kafka.ssl.client.ca }}'
          - name: KAFKA_BROKER_TLS_SECRET_NAME
            value: '{{ .Values.security.kafka.ssl.broker.secret }}'
          - name: KAFKA_BROKER_TLS_CA_LOCATION
            value: '{{ .Values.security.kafka.ssl.broker.ca }}'
