apiVersion: apps/v1
kind: Deployment
metadata:
  name: seldon-controller-manager
spec:
  template:
    spec:
      containers:
      - image: '{{ .Values.controller.image.registry }}/{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag }}'
        imagePullPolicy: '{{ .Values.controller.image.pullPolicy }}'
        name: manager
        resources:
          requests:
            cpu: '{{ .Values.controller.resources.requests.cpu }}'
            memory: '{{ .Values.controller.resources.requests.memory }}'
        env:
          - name: CONTROL_PLANE_SECURITY_PROTOCOL
            value: '{{ .Values.security.controlplane.protocol }}'            
          - name: CONTROL_PLANE_TLS_SECRET_NAME
            value: '{{ .Values.security.controlplane.ssl.client.secret }}'
          - name: CONTROL_PLANE_TLS_KEY_LOCATION
            value: '{{ .Values.security.controlplane.ssl.key }}'
          - name: CONTROL_PLANE_TLS_CRT_LOCATION
            value: '{{ .Values.security.controlplane.ssl.crt }}'
          - name: CONTROL_PLANE_TLS_CA_LOCATION
            value: '{{ .Values.security.controlplane.ssl.ca }}'
