apiVersion: mlops.seldon.io/v1alpha1
kind: ServerConfig
metadata:
  name: triton
spec:
  podSpec:
    containers:
    - image: '{{ .Values.serverConfig.rclone.image.registry }}/{{ .Values.serverConfig.rclone.image.repository }}:{{ .Values.serverConfig.rclone.image.tag }}'
      imagePullPolicy: '{{ .Values.serverConfig.rclone.image.pullPolicy }}'
      name: rclone
    - env:
      - name: SELDON_SERVER_CAPABILITIES
        value: '{{ .Values.serverConfig.triton.serverCapabilities }}'
      - name: SELDON_OVERCOMMIT_PERCENTAGE
        value: '{{ .Values.serverConfig.triton.overcommitPercentage }}'
      - name: CONTROL_PLANE_SECURITY_PROTOCOL
        value: '{{ .Values.security.controlplane.protocol }}'            
      - name: CONTROL_PLANE_TLS_SECRET_NAME
        value: '{{ .Values.security.controlplane.ssl.client.secret }}'
      - name: CONTROL_PLANE_TLS_KEY_LOCATION
        value: '{{ .Values.security.controlplane.ssl.key }}'
      - name: CONTROL_PLANE_TLS_CRT_LOCATION
        value: '{{ .Values.security.controlplane.ssl.crt }}'
      - name: CONTROL_PLANE_TLS_CA_LOCATION
        value: '{{ .Values.security.controlplane.ssl.ca }}'
      image: '{{ .Values.serverConfig.agent.image.registry }}/{{ .Values.serverConfig.agent.image.repository }}:{{ .Values.serverConfig.agent.image.tag }}'
      imagePullPolicy: '{{ .Values.serverConfig.rclone.image.pullPolicy }}'
      name: agent
    - image: '{{ .Values.serverConfig.triton.image.registry }}/{{ .Values.serverConfig.triton.image.repository }}:{{ .Values.serverConfig.triton.image.tag }}'
      imagePullPolicy: '{{ .Values.serverConfig.triton.image.pullPolicy }}'
      name: triton
      resources:
        requests:
          memory: '{{ .Values.serverConfig.triton.resources.memory }}'      
  volumeClaimTemplates:
  - name: triton-models
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: '{{ .Values.serverConfig.triton.modelVolumeStorage }}'
