apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
data:
  seldon.yaml: |
    name: testconfig
    spec:
      servers:
      - name: mlserver1
        replicas:
        - address: seldon-mlserver
          port: 9000
      models:
      - name: model1
        modelServer: mlserver1
        servers: [0]
      - name: model2
        modelServer: mlserver1
        servers: [0]
