apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- scheduler.yaml
- svc.yaml
- role.yaml
- role_binding.yaml
- serviceaccount.yaml

images:
- name: scheduler
  newName: seldonio/seldon-scheduler
  newTag: latest
