apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: scheduler
  namespace: system
  labels:
    control-plane: seldon-scheduler
spec:
  serviceName: "scheduler"  
  selector:
    matchLabels:
      control-plane: seldon-scheduler
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: seldon-scheduler
    spec:
      serviceAccountName: scheduler
      securityContext:
        runAsUser: 8888
      containers:
      - command:
        - /bin/scheduler
        args:
        - --pipeline-gateway-host=seldon-pipelinegateway
        - --pipeline-db-path=/mnt/scheduler/pipelinedb
        image: scheduler:latest
        imagePullPolicy: IfNotPresent
        name: scheduler
        ports:
        - name: xds
          containerPort: 9002
        - name: scheduler
          containerPort: 9004
        - name: agent
          containerPort: 9005
        - name: dataflow
          containerPort: 9008
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - mountPath: /mnt/scheduler
          name: scheduler-state
      terminationGracePeriodSeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: scheduler-state
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
