apiVersion: v1
kind: Service
metadata:
  name: scheduler
  labels:
    app: seldon-scheduler
spec:
  type: LoadBalancer
  ports:
  - name: xds
    port: 9002
    targetPort: xds
    protocol: TCP
  - name: scheduler
    port: 9004
    targetPort: scheduler
    protocol: TCP
  - name: scheduler-mtls
    port: 9044
    targetPort: scheduler-mtls
    protocol: TCP
  - name: agent
    port: 9005
    targetPort: agent
    protocol: TCP
  - name: dataflow
    port: 9008
    targetPort: dataflow
    protocol: TCP
  selector:
    control-plane: seldon-scheduler
