apiVersion: mlops.seldon.io/v1alpha1
kind: Server
metadata:
  name: mlserver-custom
spec:
  serverConfig: mlserver
  podSpec:
    containers:
    - image: cliveseldon/mlserver:1.2.0.dev1
      name: mlserver
