# permissions for end users to view experiments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: experiment-viewer-role
rules:
- apiGroups:
  - mlops.seldon.io
  resources:
  - experiments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mlops.seldon.io
  resources:
  - experiments/status
  verbs:
  - get
