# permissions for end users to edit explainers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: explainer-editor-role
rules:
- apiGroups:
  - mlops.seldon.io
  resources:
  - explainers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mlops.seldon.io
  resources:
  - explainers/status
  verbs:
  - get
