# permissions for end users to edit models.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: model-editor-role
rules:
- apiGroups:
  - mlops.seldon.io
  resources:
  - models
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mlops.seldon.io
  resources:
  - models/status
  verbs:
  - get
