# permissions for end users to edit pipelines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pipeline-editor-role
rules:
- apiGroups:
  - mlops.seldon.io
  resources:
  - pipelines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mlops.seldon.io
  resources:
  - pipelines/status
  verbs:
  - get
