# permissions for end users to view serverconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: serverconfig-viewer-role
rules:
- apiGroups:
  - mlops.seldon.io
  resources:
  - serverconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mlops.seldon.io
  resources:
  - serverconfigs/status
  verbs:
  - get
