# Adds namespace to all resources.
namespace: seldon-mesh

resources:
- role.yaml
- role_binding.yaml
- serviceaccount.yaml
- mlserver.yaml
- triton.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: agent
  newName: seldonio/seldon-agent
  newTag: latest
- name: mlserver
  newName: seldonio/mlserver
  newTag: 1.1.0
- name: rclone
  newName: seldonio/seldon-rclone
  newTag: latest
- name: triton
  newName: nvcr.io/nvidia/tritonserver
  newTag: 22.05-py3
