# Adds namespace to all resources.
namespace: seldon-mesh

resources:
- role.yaml
- role_binding.yaml
- serviceaccount.yaml
- mlserver.yaml
- triton.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: agent
  newName: seldonio/seldon-agent
  newTag: latest
- name: rclone
  newName: seldonio/seldon-rclone
  newTag: latest
