---
- name: Create Kind Cluster and Install MetalLB
  hosts: localhost
  roles:
    - seldonio.k8s.kind
    - seldonio.k8s.metallb
  vars:
    kind_cluster_name: ansible

    # For compatible version of image for each kind version please see https://github.com/kubernetes-sigs/kind/releases
    kind_version: v0.16.0
    kind_image_version: kindest/node:v1.24.6@sha256:97e8d00bc37a7598a0b32d1fabd155a96355c49fa0d4d4790aab0f161bf31be1

    kind_kubectl_default_namespace: seldon
