---
- name: Create Kind Cluster and Install MetalLB
  hosts: localhost
  roles:
    - seldonio.k8s.kind
    - seldonio.k8s.metallb
  vars:
    kind_cluster_name: ansible

    # For compatible version of image for each kind version please see https://github.com/kubernetes-sigs/kind/releases
    kind_version: v0.17.0
    kind_image_version: kindest/node:v1.24.7@sha256:577c630ce8e509131eab1aea12c022190978dd2f745aac5eb1fe65c0807eb315

    kind_kubectl_default_namespace: seldon
