apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- role.yaml
- role_binding.yaml
- serviceaccount.yaml

images:
- name: hodometer
  newName: seldonio/seldon-hodometer
  newTag: latest
