apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hodometer-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hodometer-role
subjects:
- kind: ServiceAccount
  name: hodometer
