# permissions to get TLS secrets
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hodometer-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
