apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - /manager
        args:
        - --health-probe-bind-address=:8081
        - --leader-elect
        - --scheduler-host=$(SELDON_SCHEDULER_SVC)
        - --scheduler-plaintxt-port=$(SELDON_SCHEDULER_PLAINTXT_PORT)
        - --scheduler-tls-port=$(SELDON_SCHEDULER_TLS_PORT)        
        - --namespace=$(POD_NAMESPACE)
        image: controller:latest
        imagePullPolicy: IfNotPresent
        name: manager
        env:
          - name: SELDON_SCHEDULER_SVC
            value: "seldon-scheduler"
          - name: SELDON_SCHEDULER_PLAINTXT_PORT
            value: "9004"
          - name: SELDON_SCHEDULER_TLS_PORT
            value: "9044"
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: SCHEDULER_TLS_SECRET_NAME
            value: ""
          - name: SCHEDULER_TLS_FOLDER_PATH
            value: ""
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        # TODO(user): Configure the resources accordingly based on the project requirements.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
