apiVersion: v1
kind: Service
metadata:
  name: myapps
  namespace: traefik-v2
spec:
  ports:
    - protocol: TCP
      name: web
      port: 80
  selector:
    app: traefik-ingress-lb
  type: LoadBalancer
