# permissions for end users to edit inferenceexplainers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: inferenceexplainer-editor-role
rules:
- apiGroups:
  - mlops.seldon.io
  resources:
  - inferenceexplainers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mlops.seldon.io
  resources:
  - inferenceexplainers/status
  verbs:
  - get
