# permissions for end users to edit inferenceartifacts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: inferenceartifact-editor-role
rules:
- apiGroups:
  - mlops.seldon.io
  resources:
  - inferenceartifacts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mlops.seldon.io
  resources:
  - inferenceartifacts/status
  verbs:
  - get
