# permissions for end users to edit inferenceservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: inferenceserver-editor-role
rules:
- apiGroups:
  - mlops.seldon.io
  resources:
  - inferenceservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mlops.seldon.io
  resources:
  - inferenceservers/status
  verbs:
  - get
