# permissions for end users to edit inferenceserverinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: inferenceserverinstance-editor-role
rules:
- apiGroups:
  - mlops.seldon.io
  resources:
  - inferenceserverinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mlops.seldon.io
  resources:
  - inferenceserverinstances/status
  verbs:
  - get
