# permissions for end users to view inferencegraphs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: inferencegraph-viewer-role
rules:
- apiGroups:
  - mlops.seldon.io
  resources:
  - inferencegraphs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mlops.seldon.io
  resources:
  - inferencegraphs/status
  verbs:
  - get
