# Default values for seldon-core.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cluster_manager:
  image:
    tag: "0.2.14"
apife:
  image:
    tag: "0.0.4"

kafka_core:
  image:
    tag: "0.1"
zookeeper:
  image:
    tag: "1.0"
redis:
  image:
    tag: "4.0.1"

# set the cluster manager client secret
#cluster_manager_client_secret:


# set the JAVA_OPTS
#java_opts: "-agentlib:jdwp=transport=dt_socket,address=127.0.0.1:8000,server=y,suspend=n"
java_opts: ""

# set the SPRING_OPTS
#spring_opts: "--io.seldon.clustermanager.engine-container-image-and-version=seldonio/engine:0.1.5 --io.seldon.clustermanager.istio-enabled=false"
spring_opts: "--io.seldon.clustermanager.istio-enabled=false"

# Set the type of service for Cluster Manager
#seldon_cluster_manager_service_type: LoadBalancer
cluster_manager_service_type: NodePort

