# Default values for seldon-core.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cluster_manager:
  enabled: true
  image:
    tag: "0.2.16"
    pull_policy: "IfNotPresent"
apife:
  image:
    tag: "0.0.7"
    pull_policy: "IfNotPresent"
engine:
  image:
    tag: "0.1.6"

kafka_core:
  image:
    tag: "0.1"
zookeeper:
  image:
    tag: "1.0"
redis:
  image:
    tag: "4.0.1"
kube_apiserver:
  enabled: false


alertmanager:
  # config disabled by default, create file "/files/alertmanager/config.yaml" then enable
  config:
    enabled: false


# set the cluster manager client secret
#cluster_manager_client_secret:

# set the grafana admin password
#grafana_prom_admin_password:

# set the JAVA_OPTS
#java_opts: "-agentlib:jdwp=transport=dt_socket,address=127.0.0.1:8000,server=y,suspend=n"
java_opts: ""

# set the SPRING_OPTS
#spring_opts: "--io.seldon.clustermanager.engine-container-image-and-version=seldonio/engine:0.1.5 --io.seldon.clustermanager.istio-enabled=false"
spring_opts: "--io.seldon.clustermanager.istio-enabled=false"

# Set the type of service for Grafana Prom
#grafana_prom_service_type: LoadBalancer
grafana_prom_service_type: NodePort

# Set the type of service for apife
#apife_service_type: LoadBalancer
apife_service_type: NodePort

# Persist data to a persitent volume
persistence:
  enabled: true

