# Default values for seldon-core.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cluster_manager:
  image:
    tag: "0.2.14"
apife:
  image:
    tag: "0.0.4"

kafka_core:
  image:
    tag: "0.1"
zookeeper:
  image:
    tag: "1.0"
redis:
  image:
    tag: "4.0.1"

# set the cluster manager client secret
#cluster_manager_client_secret:

