baseURL = "http://localhost"
#baseURL = "https://seldon-dev.gitlab.io"
languageCode = "en-us"
title = "Seldon Core Documentation"

canonifyURLs = true

# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-docdock"

# For search functionnality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
themeVariant = "gold"
