{{- if .Values.cluster_manager.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: cluster-manager-client-secret
type: Opaque
data:
  {{- if .Values.cluster_manager_client_secret }}
  cluster-manager-client-secret.txt: {{ .Values.cluster_manager_client_secret | b64enc | quote }}
  {{- else }}
  cluster-manager-client-secret.txt: {{ randAlphaNum 15 | b64enc | quote }}
  {{- end }}
{{- end }}
