---
apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: seldon-cluster-manager
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: seldon-cluster-manager-server
      spec:
        containers:
        - env:
          - name: JAVA_OPTS
            value: -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:8000,server=y,suspend=n
          - name: SELDON_CLUSTER_MANAGER_ZK_SERVERS
            value: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
          - name: SELDON_CLUSTER_MANAGER_REDIS_HOST
            value: redis
          - name: SELDON_CLUSTER_MANAGER_POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: SELDON_CLUSTER_MANAGER_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                key: cluster-manager-client-secret.txt
                name: cluster-manager-client-secret
          image: seldonio/cluster-manager:0.2.14
          name: seldon-cluster-manager-container
          ports:
          - containerPort: 8080
            protocol: TCP
- apiVersion: v1
  kind: Service
  metadata:
    name: seldon-cluster-manager
  spec:
    ports:
    - name: client
      nodePort: 30030
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: seldon-cluster-manager-server
    sessionAffinity: None
    type: NodePort
kind: List
metadata: {}

