name: lint
on:
  pull_request:
jobs:
  lint:
    name: lint
    if: github.repository == 'SeldonIO/seldon-core-v2' # Do not run this on forks.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.4'
      - name: lint-operator
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42.1
          working-directory: operator
          skip-go-installation: true
      - name: lint-scheduler
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42.1
          working-directory: scheduler
          skip-go-installation: true
