name: Python Lint

on:
  push:
    branches: [ master, v*-release ]
  pull_request:
    branches: [ master, v*-release ]

jobs:
  python-lint:

    runs-on: ubuntu-18.04
    container: seldonio/python-builder:0.5

    steps:
    - uses: actions/checkout@v2
    - name: lint-python
      run: |
        make -C python install_dev lint

