name: Python Tests

on:
  push:
    branches: [ master, v*-release ]
  pull_request:
    branches: [ master, v*-release ]

jobs:
  python-tests:

    runs-on: ubuntu-18.04
    container: seldonio/python-builder:0.5

    steps:
    - uses: actions/checkout@v2
    - name: test-python
      run: |
        make -C python update_package install_dev test

